In [39]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/inventory-management/Inventory Data.xlsx

In [40]:
excel="/kaggle/input/inventory-management/Inventory Data.xlsx"

In [41]:
past=pd.read_excel(excel,sheet_name=0)
stock=pd.read_excel(excel,sheet_name=1)
past
stock

,SKU ID,Current Stock Quantity,Units (Nos/Kg),Average Lead Time (days),Maximum Lead Time (days),Unit Price
0,1009AA,7210.0,Kg,30,48,28.76326
1,1077CA,46516.0,Kg,45,70,22.97770
2,1083AA,48210.0,Kg,45,68,29.02000
3,1116CA,33398.0,Kg,90,140,32.80000
4,1126CA,39270.0,Kg,45,62,32.80000
...,...,...,...,...,...,...
298,3579CA,116.0,Kg,120,187,86.65000
299,3590BA,145.0,Kg,120,160,115.08500
300,3610AA,275.0,Kg,120,188,156.16000
301,3616CA,331.0,Kg,120,167,433.10000
302,3619CA,36357.0,Kg,15,22,0.74550

In [42]:
df=pd.concat([past,stock],axis=0)
df

,Order Date,SKU ID,Order Quantity,Current Stock Quantity,Units (Nos/Kg),Average Lead Time (days),Maximum Lead Time (days),Unit Price
0,2022-11-19,3084CA,1.00,NaN,NaN,NaN,NaN,NaN
1,2022-06-30,2621AA,20.00,NaN,NaN,NaN,NaN,NaN
2,2023-04-19,1193BA,147.00,NaN,NaN,NaN,NaN,NaN
3,2023-05-21,1971AA,10.00,NaN,NaN,NaN,NaN,NaN
4,2022-03-31,3177CA,56.25,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
298,NaT,3579CA,NaN,116.0,Kg,120.0,187.0,86.6500
299,NaT,3590BA,NaN,145.0,Kg,120.0,160.0,115.0850
300,NaT,3610AA,NaN,275.0,Kg,120.0,188.0,156.1600
301,NaT,3616CA,NaN,331.0,Kg,120.0,167.0,433.1000
302,NaT,3619CA,NaN,36357.0,Kg,15.0,22.0,0.7455

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34222 entries, 0 to 302
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order Date                33919 non-null  datetime64[ns]
 1   SKU ID                    34222 non-null  object
 2   Order Quantity            33919 non-null  float64
 3   Current Stock Quantity    303 non-null    float64
 4   Units (Nos/Kg)            303 non-null    object
 5   Average Lead Time (days)  303 non-null    float64
 6   Maximum Lead Time (days)  303 non-null    float64
 7   Unit Price                303 non-null    float64
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 2.3+ MB

In [49]:
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [85]:
numerical_columns = df11.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_columns = df11.select_dtypes(include=['object']).columns.tolist()
numerical_pipeline = Pipeline([
    ,
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', sparse=False))
])


preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_pipeline, numerical_columns),
        ('cat', categorical_pipeline, categorical_columns)
    ])


main_pipeline = Pipeline([
    ('preprocessor', preprocessor)
])

In [ ]:
df_new = main_pipeline.fit_transform(df11)
df_new

In [73]:
num_imputer = SimpleImputer(strategy='mean')
cat_imputer = SimpleImputer(strategy='most_frequent')

# Impute numerical columns
imputed_num = pd.DataFrame(
    num_imputer.fit_transform(df[numerical_columns]),
    columns=numerical_columns,
    index=df.index
)

# Impute categorical columns
imputed_cat = pd.DataFrame(
    cat_imputer.fit_transform(df[categorical_columns]),
    columns=categorical_columns,
    index=df.index
)

# Combine imputed numerical and categorical data
df11 = pd.concat([imputed_num, imputed_cat], axis=1)
df11

,Order Quantity,Current Stock Quantity,Average Lead Time (days),Maximum Lead Time (days),Unit Price,year,month,day,SKU ID,Units (Nos/Kg)
0,1.000000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,11.000000,19.000000,3084CA,Kg
1,20.000000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,6.000000,30.000000,2621AA,Kg
2,147.000000,6586.761003,52.937294,76.834983,4202.477681,2023.00000,4.000000,19.000000,1193BA,Kg
3,10.000000,6586.761003,52.937294,76.834983,4202.477681,2023.00000,5.000000,21.000000,1971AA,Kg
4,56.250000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,3.000000,31.000000,3177CA,Kg
...,...,...,...,...,...,...,...,...,...,...
298,432.793196,116.000000,120.000000,187.000000,86.650000,2022.42631,6.055898,15.492526,3579CA,Kg
299,432.793196,145.000000,120.000000,160.000000,115.085000,2022.42631,6.055898,15.492526,3590BA,Kg
300,432.793196,275.000000,120.000000,188.000000,156.160000,2022.42631,6.055898,15.492526,3610AA,Kg
301,432.793196,331.000000,120.000000,167.000000,433.100000,2022.42631,6.055898,15.492526,3616CA,Kg
302,432.793196,36357.000000,15.000000,22.000000,0.745500,2022.42631,6.055898,15.492526,3619CA,Kg

In [75]:
df['year'] = df['Order Date'].dt.year
df['month'] = df['Order Date'].dt.month  
df['day'] = df['Order Date'].dt.day

**inventory turnover ratio**

In [76]:
df11["Inventory Turnover Ratio"] = df11["Order Quantity"] / (df11["Current Stock Quantity"] / 2)

**safety stock**

In [77]:
df11["Safety Stock"] = 1.65 * (0.2 * df11["Order Quantity"]) * df11["Average Lead Time (days)"].apply(np.sqrt)

**Reorder Points (ROP)**

In [78]:
df11["Daily Demand"] = df11["Order Quantity"] / 30
df11["Reorder Point"] = (df11["Daily Demand"] * df11["Average Lead Time (days)"]) + df11["Safety Stock"]

**Stock classification (status)**

In [79]:
def classify_stock_status(row):
    if row["Current Stock Quantity"] >= row["Reorder Point"] + row["Safety Stock"]:
        return "Safe"
    elif row["Current Stock Quantity"] < row["Reorder Point"] and row["Current Stock Quantity"] > row["Safety Stock"]:
        return "Reorder"
    else:
        return "Stockout"

df11["Stock Status"] = df11.apply(classify_stock_status, axis=1)

In [80]:
df11

,Order Quantity,Current Stock Quantity,Average Lead Time (days),Maximum Lead Time (days),Unit Price,year,month,day,SKU ID,Units (Nos/Kg),Inventory Turnover Ratio,Safety Stock,Daily Demand,Reorder Point,Stock Status
0,1.000000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,11.000000,19.000000,3084CA,Kg,0.000304,2.401015,0.033333,4.165591,Safe
1,20.000000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,6.000000,30.000000,2621AA,Kg,0.006073,48.020293,0.666667,83.311822,Safe
2,147.000000,6586.761003,52.937294,76.834983,4202.477681,2023.00000,4.000000,19.000000,1193BA,Kg,0.044635,352.949152,4.900000,612.341891,Safe
3,10.000000,6586.761003,52.937294,76.834983,4202.477681,2023.00000,5.000000,21.000000,1971AA,Kg,0.003036,24.010146,0.333333,41.655911,Safe
4,56.250000,6586.761003,52.937294,76.834983,4202.477681,2022.00000,3.000000,31.000000,3177CA,Kg,0.017080,135.057073,1.875000,234.314499,Safe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,432.793196,116.000000,120.000000,187.000000,86.650000,2022.42631,6.055898,15.492526,3579CA,Kg,7.461952,1564.533934,14.426440,3295.706716,Stockout
299,432.793196,145.000000,120.000000,160.000000,115.085000,2022.42631,6.055898,15.492526,3590BA,Kg,5.969561,1564.533934,14.426440,3295.706716,Stockout
300,432.793196,275.000000,120.000000,188.000000,156.160000,2022.42631,6.055898,15.492526,3610AA,Kg,3.147587,1564.533934,14.426440,3295.706716,Stockout
301,432.793196,331.000000,120.000000,167.000000,433.100000,2022.42631,6.055898,15.492526,3616CA,Kg,2.615065,1564.533934,14.426440,3295.706716,Stockout
302,432.793196,36357.000000,15.000000,22.000000,0.745500,2022.42631,6.055898,15.492526,3619CA,Kg,0.023808,553.146277,14.426440,769.542875,Safe

In [81]:
df11.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34222 entries, 0 to 302
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Order Quantity            34222 non-null  float64
 1   Current Stock Quantity    34222 non-null  float64
 2   Average Lead Time (days)  34222 non-null  float64
 3   Maximum Lead Time (days)  34222 non-null  float64
 4   Unit Price                34222 non-null  float64
 5   year                      34222 non-null  float64
 6   month                     34222 non-null  float64
 7   day                       34222 non-null  float64
 8   SKU ID                    34222 non-null  object
 9   Units (Nos/Kg)            34222 non-null  object
 10  Inventory Turnover Ratio  34222 non-null  float64
 11  Safety Stock              34222 non-null  float64
 12  Daily Demand              34222 non-null  float64
 13  Reorder Point             34222 non-null  float64
 14  Stock Status              34222 non-null  object
dtypes: float64(12), object(3)
memory usage: 4.2+ MB

In [84]:
df11.to_csv('imputed_data.csv', index=False)

In [ ]:
etl